workflows:
  pine-city-zoo-android:
    name: "Android Build"
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "itvarsity.co.za.pinecity.zoo"
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
